In [7]:
import matplotlib.pyplot as plt
import pandas as pd
import numpy as np


data1 = pd.read_csv('../data/food_risk_o.csv')
data1.head(3)

,店铺ID,店铺名,开始时间,风险值,地区名,销售额
0,3d8ab846-7725-11ea-98c9-525400c74cae,1+7水饺店(金科世界城店),2019-01-01,0.147242,滨湖区,313.5
1,3d8ab846-7725-11ea-98c9-525400c74cae,1+7水饺店(金科世界城店),2019-02-01,0.187812,滨湖区,376.2
2,3d8ab846-7725-11ea-98c9-525400c74cae,1+7水饺店(金科世界城店),2019-03-01,0.313739,滨湖区,501.6

In [8]:
data1.shape

(70943, 6)

In [9]:
data2 = pd.read_csv('../data/food_record.csv')
data2.head(3)

                                   店铺ID             店铺名        开始时间       风险值
0  3d8ab846-7725-11ea-98c9-525400c74cae  1+7水饺店(金科世界城店)  2019-01-01  0.147242
1  3d8ab846-7725-11ea-98c9-525400c74cae  1+7水饺店(金科世界城店)  2019-02-01  0.187812
2  3d8ab846-7725-11ea-98c9-525400c74cae  1+7水饺店(金科世界城店)  2019-03-01  0.313739

In [10]:
data2.shape

(72502, 4)

In [11]:
df = pd.merge(data1,data2,how='right',on=['店铺ID','开始时间'])
df.head(3)

,店铺ID,店铺名_x,开始时间,风险值_x,地区名,销售额,店铺名_y,风险值_y
0,3d8ab846-7725-11ea-98c9-525400c74cae,1+7水饺店(金科世界城店),2019-01-01,0.147242,滨湖区,313.5,1+7水饺店(金科世界城店),0.147242
1,3d8ab846-7725-11ea-98c9-525400c74cae,1+7水饺店(金科世界城店),2019-02-01,0.187812,滨湖区,376.2,1+7水饺店(金科世界城店),0.187812
2,3d8ab846-7725-11ea-98c9-525400c74cae,1+7水饺店(金科世界城店),2019-03-01,0.313739,滨湖区,501.6,1+7水饺店(金科世界城店),0.313739

In [12]:
df.shape

(72502, 8)

In [13]:
# 删除多余列
df = df.drop(['店铺名_y','风险值_y'],axis=1)
df

,店铺ID,店铺名_x,开始时间,风险值_x,地区名,销售额
0,3d8ab846-7725-11ea-98c9-525400c74cae,1+7水饺店(金科世界城店),2019-01-01,0.147242,滨湖区,313.5
1,3d8ab846-7725-11ea-98c9-525400c74cae,1+7水饺店(金科世界城店),2019-02-01,0.187812,滨湖区,376.2
2,3d8ab846-7725-11ea-98c9-525400c74cae,1+7水饺店(金科世界城店),2019-03-01,0.313739,滨湖区,501.6
3,3d8ab846-7725-11ea-98c9-525400c74cae,1+7水饺店(金科世界城店),2019-04-01,0.462676,滨湖区,627.0
4,3d8ab846-7725-11ea-98c9-525400c74cae,1+7水饺店(金科世界城店),2019-05-01,0.523725,滨湖区,752.4
...,...,...,...,...,...,...
72497,dcedfb83-7727-11ea-98c9-525400c74cae,龙门铁板炒饭（崇安寺步行街店）,2019-08-01,0.635473,梁溪区,1349.4
72498,dcedfb83-7727-11ea-98c9-525400c74cae,龙门铁板炒饭（崇安寺步行街店）,2019-09-01,0.549814,梁溪区,1141.8
72499,dcedfb83-7727-11ea-98c9-525400c74cae,龙门铁板炒饭（崇安寺步行街店）,2019-10-01,0.372998,梁溪区,1038.0
72500,dcedfb83-7727-11ea-98c9-525400c74cae,龙门铁板炒饭（崇安寺步行街店）,2019-11-01,0.268777,梁溪区,934.2
72501,dcedfb83-7727-11ea-98c9-525400c74cae,龙门铁板炒饭（崇安寺步行街店）,2019-12-01,0.247738,梁溪区,726.6

In [14]:
#  查看重复值情况
df.duplicated().sum()

0

In [15]:
# 查看缺失值情况
df.isnull().sum()

店铺ID        0
店铺名_x    1559
开始时间        0
风险值_x    1559
地区名      1559
销售额      1559
dtype: int64

In [16]:
# 删除空值行
df.dropna()

,店铺ID,店铺名_x,开始时间,风险值_x,地区名,销售额
0,3d8ab846-7725-11ea-98c9-525400c74cae,1+7水饺店(金科世界城店),2019-01-01,0.147242,滨湖区,313.5
1,3d8ab846-7725-11ea-98c9-525400c74cae,1+7水饺店(金科世界城店),2019-02-01,0.187812,滨湖区,376.2
2,3d8ab846-7725-11ea-98c9-525400c74cae,1+7水饺店(金科世界城店),2019-03-01,0.313739,滨湖区,501.6
3,3d8ab846-7725-11ea-98c9-525400c74cae,1+7水饺店(金科世界城店),2019-04-01,0.462676,滨湖区,627.0
4,3d8ab846-7725-11ea-98c9-525400c74cae,1+7水饺店(金科世界城店),2019-05-01,0.523725,滨湖区,752.4
...,...,...,...,...,...,...
72497,dcedfb83-7727-11ea-98c9-525400c74cae,龙门铁板炒饭（崇安寺步行街店）,2019-08-01,0.635473,梁溪区,1349.4
72498,dcedfb83-7727-11ea-98c9-525400c74cae,龙门铁板炒饭（崇安寺步行街店）,2019-09-01,0.549814,梁溪区,1141.8
72499,dcedfb83-7727-11ea-98c9-525400c74cae,龙门铁板炒饭（崇安寺步行街店）,2019-10-01,0.372998,梁溪区,1038.0
72500,dcedfb83-7727-11ea-98c9-525400c74cae,龙门铁板炒饭（崇安寺步行街店）,2019-11-01,0.268777,梁溪区,934.2
72501,dcedfb83-7727-11ea-98c9-525400c74cae,龙门铁板炒饭（崇安寺步行街店）,2019-12-01,0.247738,梁溪区,726.6